In [68]:
import numpy as np
import matplotlib.pyplot as plt

with open('sample_input.txt') as f:
    scanners = [[[int(n) for n in beacon.split(',')] for beacon in scanner] for scanner in [
        s.split('\n')[1:] for s in ''.join(f.readlines()).split('\n\n')]]

# we keep scanners[0] the same orientation
# create 24 distinct orientations for all other scanners (?)

# for every beacon in each scanner:
    # get relative coordinate to every other beacon and store in [25 x 25 x 3]

rel_coord_matrices = []

for scanner in scanners:
    num_beacons = len(scanner)
    rel_coord_matrix = np.zeros(shape=(num_beacons, num_beacons, 3))
    for (i, b1) in enumerate(scanner):
        for (j, b2) in enumerate(scanner):
            rel_coord_matrix[i][j] = (np.array(b1) - np.array(b2))
    rel_coord_matrices.append(rel_coord_matrix)

# print(rel_coord_matrices[0])
print(rel_coord_matrices[1])



[[[ 0.000e+00  0.000e+00  0.000e+00]
  [ 8.100e+01 -1.000e+00  1.630e+02]
  [ 1.710e+02 -4.950e+02  9.390e+02]
  ...
  [-1.210e+02  9.210e+02  1.289e+03]
  [-6.900e+01  7.760e+02  1.197e+03]
  [ 1.330e+02 -4.670e+02  9.680e+02]]

 [[-8.100e+01  1.000e+00 -1.630e+02]
  [ 0.000e+00  0.000e+00  0.000e+00]
  [ 9.000e+01 -4.940e+02  7.760e+02]
  ...
  [-2.020e+02  9.220e+02  1.126e+03]
  [-1.500e+02  7.770e+02  1.034e+03]
  [ 5.200e+01 -4.660e+02  8.050e+02]]

 [[-1.710e+02  4.950e+02 -9.390e+02]
  [-9.000e+01  4.940e+02 -7.760e+02]
  [ 0.000e+00  0.000e+00  0.000e+00]
  ...
  [-2.920e+02  1.416e+03  3.500e+02]
  [-2.400e+02  1.271e+03  2.580e+02]
  [-3.800e+01  2.800e+01  2.900e+01]]

 ...

 [[ 1.210e+02 -9.210e+02 -1.289e+03]
  [ 2.020e+02 -9.220e+02 -1.126e+03]
  [ 2.920e+02 -1.416e+03 -3.500e+02]
  ...
  [ 0.000e+00  0.000e+00  0.000e+00]
  [ 5.200e+01 -1.450e+02 -9.200e+01]
  [ 2.540e+02 -1.388e+03 -3.210e+02]]

 [[ 6.900e+01 -7.760e+02 -1.197e+03]
  [ 1.500e+02 -7.770e+02 -1.034e+03]


In [64]:
rel_coord_matrix.shape

(26, 26, 3)

In [14]:
x2 = 0
x = 101
        
while x2 < x:
    tempX = x
    x2 += x2 * 10 + x % 10
    x = x // 10

    print(x2)
    print(x)

1
10
11
1
