In [24]:
import numpy as np

with open('test_input.txt', 'r') as f:
    lines = f.readlines()

lines = [[int(c) for c in line.strip()] for line in lines] # gets rid of \n
trees = np.array(lines)
not_seen = np.ones_like(trees)

# if I want vanilla rotation:
def rotate(A):
    A[:] = map(list, zip(*A[::-1]))

sum = 0

for _ in range(4):
    curr_max_height = np.zeros(trees.shape[0]) - 1
    for (i, tree_row) in enumerate(trees):
        diff = tree_row - curr_max_height
        filter = np.where(diff > 0, 1, 0) 
        curr_max_height += filter * diff
        
        filter *= not_seen[i]
        sum += np.sum(filter)
        not_seen[i] *= (1 - filter)
    
    trees = np.rot90(trees)
    not_seen = np.rot90(not_seen)

print(sum)
# assert(sum == 1845)


21


In [125]:
#     [a b c d e]
# - [a b c d e]
# this was a terrible approach and I regret it

with open('input.txt', 'r') as f:
    lines = f.readlines()

lines = [[int(c) for c in line.strip()] for line in lines] # gets rid of \n
trees = np.array(lines)

total_scores = np.ones_like(trees)
for _ in range(4):
    scores = np.zeros_like(trees)
    not_blocked = np.ones_like(trees)
    for (i, tree_row) in enumerate(trees):
        for j in range(len(tree_row)):
            next = np.ones_like(tree_row) * 100
            next[:-(j+1)] = tree_row[j+1:]
            diff = next - tree_row
            next_is_shorter = diff < 0
            # indexing because we don't want to update the edges
            scores[i][:-j-1] += not_blocked[i][:-j-1]
            not_blocked[i] *= next_is_shorter
        scores[i][0] = 0
    total_scores *= scores
    total_scores = np.rot90(total_scores)
    trees = np.rot90(trees)
ans = max(total_scores.flatten())

print(total_scores)
print(ans)

assert(ans == 230112)

[[ 0  0  0 ...  0  0  0]
 [ 0  1  2 ...  4  1  0]
 [ 0  1  4 ...  1 30  0]
 ...
 [ 0  1  6 ...  1 20  0]
 [ 0  3  1 ...  1  2  0]
 [ 0  0  0 ...  0  0  0]]
230112
