In [6]:
import re
import numpy as np

input_list = [4, 75, 74, 31, 76, 79, 27, 19, 69, 46, 98, 59, 83, 23, 90, 52, 87, 6, 11, 92, 80, 51, 43, 5, 94, 17, 15, 67, 25, 30, 48, 47, 62, 71, 85, 58, 60, 1, 72, 99, 3, 35, 42, 10, 96, 49, 37, 36, 8,
              44, 70, 40, 45, 39, 0, 63, 2, 78, 68, 53, 50, 77, 20, 55, 38, 86, 54, 93, 26, 88, 12, 91, 95, 34, 9, 14, 33, 66, 41, 13, 28, 57, 29, 73, 56, 22, 89, 21, 64, 61, 32, 65, 97, 84, 18, 82, 81, 7, 16, 24]
# input_list = [7, 4, 9, 5, 11, 17, 23, 2, 0, 14, 21, 24,10, 16, 13, 6, 15, 25, 12, 22, 18, 20, 8, 19, 3, 26, 1]


with open('input.txt') as f:
    raw_data = f.readlines()
    raw_data = ('').join(raw_data).split('\n\n')

    boards = []
    for raw_matrix in raw_data:
        boards.append([[int(n) for n in re.split("\s+", row) if n != '']
                      for row in raw_matrix.split('\n')])

    boards = np.array(boards)


def callNum(n, board, ticks):
    for (i, row) in enumerate(board):
        for (j, cell) in enumerate(row):
            if cell == n:
                ticks[i][j] = 1
                return


def checkBingo(board, ticks):
    # check for horizontal
    # if any(sum == 5 for sum in np.sum(ticks, axis = 0)):
    #     return True
    # # check for vertical
    # if any(sum == 5 for sum in np.sum(ticks, axis = 0)):
    #     return True
    # else:
    #     return False
    for row in ticks:
        if all(n == 1 for n in row):
            return np.sum(np.sum(board*ticks))

    ticks_t = np.transpose(ticks)
    for col in ticks_t:
        if all(n == 1 for n in col):
            return np.sum(np.sum(board*ticks))
    else:
        return False


ticks = np.zeros((len(boards), 5, 5))

boardNum = len(ticks)
found_bingo = False
for num in input_list:
    if not found_bingo:
        success_boards = []
        for (i, board) in enumerate(boards):
            callNum(num, board, ticks[i])
            success = checkBingo(board, ticks[i])
            if (success != False):
                if (len(boards) == 1):
                    sum = np.sum(np.sum(board)) - success
                    print(board)
                    print(ticks[i])
                    print(sum)
                    print(num)
                    print(int(sum * num))
                    found_bingo = True
                    break
                else:
                    success_boards.append(i)
        boards = np.delete(boards, success_boards, axis=0)
        ticks = np.delete(ticks, success_boards, axis=0)


[[20 32 76 50 55]
 [ 4 70 14 36 82]
 [74 10 97 26 87]
 [61 83 56 98 71]
 [64 38  8 65 92]]
[[1. 0. 1. 1. 1.]
 [1. 1. 1. 1. 0.]
 [1. 1. 0. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 0. 1.]]
276.0
61
16836


In [88]:
boards.shape

(99, 5, 5)