In [59]:
import numpy as np

with open('input.txt') as f:
    raw_text = f.readlines()
    caveMap = [[int(n) for n in row.split('\n')[0]] for row in raw_text]

width, height = [len(caveMap[0]), len(caveMap)]

lowPointMap = [[0] * width]*height
lowPointMap = np.zeros((height, width))

lowPoints = []

for (i, row) in enumerate(caveMap):
    for (j, n) in enumerate(row):
        # print(n)
        # left
        if (i > 0):
            if caveMap[i-1][j] <= n:
                continue
        # right
        if (i < height-1):
            if caveMap[i+1][j] <= n:
                continue
        # up
        if (j > 0):
            if caveMap[i][j-1] <= n:
                continue

        # down
        if (j < width - 1):
            if caveMap[i][j+1] <= n:
                continue

        lowPoints.append((i, j))
        lowPointMap[i][j] = 1 + n

sum(sum(lowPointMap))


570.0

In [61]:
# part 2

def searchNeighbors(i, j):
    successNeighbors = []
    n = caveMap[i][j]
    if (i > 0):
        if caveMap[i-1][j] > n and caveMap[i-1][j] != 9:
            successNeighbors.append((i-1, j))
    # right
    if (i < height-1):
        if caveMap[i+1][j] > n and caveMap[i+1][j] != 9:
            successNeighbors.append((i+1, j))
    # up
    if (j > 0):
        if caveMap[i][j-1] > n and caveMap[i][j-1] != 9:
            successNeighbors.append((i, j-1))

    # down
    if (j < width - 1):
        if caveMap[i][j+1] > n and caveMap[i][j+1] != 9:
            successNeighbors.append((i, j+1))

    return successNeighbors


basinSizeMap = np.zeros((height, width))

for p in lowPoints:
    # new points
    neighbors = searchNeighbors(p[0], p[1])
    visitedSet = set(neighbors + [p])
    basinSize = 1

    while len(neighbors) > 0:
        basinSize += len(neighbors)
        neighborsCopy = []
        for n in neighbors:
            neighborsCopy += searchNeighbors(n[0], n[1])
        neighborsCopy = set(neighborsCopy) - visitedSet
        # print(neighborsCopy)
        visitedSet = visitedSet | neighborsCopy
        neighbors = list(neighborsCopy)

    basinSizeMap[p[0]][p[1]] = len(list(visitedSet))

print(basinSizeMap)
basinSizeMap = basinSizeMap.flatten()
basinSizeMap.sort()
print(basinSizeMap[-3:])
print(np.prod(basinSizeMap[-3:]))


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[ 92.  94. 104.]
899392.0


In [47]:
caveMap

[[2, 1, 9, 9, 9, 4, 3, 2, 1, 0],
 [3, 9, 8, 7, 8, 9, 4, 9, 2, 1],
 [9, 8, 5, 6, 7, 8, 9, 8, 9, 2],
 [8, 7, 6, 7, 8, 9, 6, 7, 8, 9],
 [9, 8, 9, 9, 9, 6, 5, 6, 7, 8]]

In [ ]:
#470162 is too low
# 1302210 is too high